;THIS CODE TAKES TWO NUMBERS FROM THE USER AND PRINTS THEIR PRODUCT
;THE INPUTS AND THE OUTPUT ARE LESS THAN 10
INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H
.DATA
A DB ?
B DB ?
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    PRINTN ' ENTER THE FIRST NUMBER'
    MOV AH,1
    INT 21H
    MOV DL,AL   
    
    PRINTN
    
    PRINTN 'ENTER THE SECOND NUMBER'
    INT 21H
    MOV B,AL     
    PRINTN
    
    PRINTN 'THE NUMBERS ARE'
    
    MOV A,DL
    MOV AH,2
    INT 21H 
    
    PRINTN
    
    MOV DL,B
    INT 21H   
    
    XOR AX,AX
    XOR BX,BX
     
    MOV AL,A 
    SUB AL,48
    MOV BL,B 
    SUB BL,48
    MUL BL
    
    PRINTN
    
    MOV DL,AL 
    ADD DL,48
    PRINTN 'THE PRODUCT IS '
    MOV AH,2
    INT 21H
    
    MAIN ENDP
END MAIN